"""empty message

Revision ID: 2c7dd3229601
Revises: f07b4e5d7aa4
Create Date: 2016-06-04 18:00:27.811819

"""

# revision identifiers, used by Alembic.
revision = '2c7dd3229601'
down_revision = 'f07b4e5d7aa4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['fb_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###
