"""empty message

Revision ID: 5206ce7720c5
Revises: 0d6d59c8453b
Create Date: 2016-06-04 15:11:09.172151

"""

# revision identifiers, used by Alembic.
revision = '5206ce7720c5'
down_revision = '0d6d59c8453b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('expiration_time', sa.DECIMAL(precision=16), nullable=False),
    sa.Column('min_bid', sa.DECIMAL(precision=8), nullable=False),
    sa.Column('min_increment_bid', sa.DECIMAL(precision=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expiration_time'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('min_bid'),
    sa.UniqueConstraint('min_increment_bid'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    ### end Alembic commands ###
