"""empty message

Revision ID: 8049f3b66de2
Revises: 2c7dd3229601
Create Date: 2016-06-05 09:18:39.402166

"""

# revision identifiers, used by Alembic.
revision = '8049f3b66de2'
down_revision = '2c7dd3229601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'status')
    ### end Alembic commands ###
