"""empty message

Revision ID: 8126c51aaa7b
Revises: 8049f3b66de2
Create Date: 2016-06-05 09:45:56.395272

"""

# revision identifiers, used by Alembic.
revision = '8126c51aaa7b'
down_revision = '8049f3b66de2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
