"""empty message

Revision ID: a8fcebaaa005
Revises: 8126c51aaa7b
Create Date: 2016-06-05 09:47:16.860262

"""

# revision identifiers, used by Alembic.
revision = 'a8fcebaaa005'
down_revision = '8126c51aaa7b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'1'"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'1'"))
    ### end Alembic commands ###
