"""empty message

Revision ID: ce07d0be61f6
Revises: af7165fb8ba3
Create Date: 2016-06-04 14:10:09.611139

"""

# revision identifiers, used by Alembic.
revision = 'ce07d0be61f6'
down_revision = 'af7165fb8ba3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_id', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'fb_id')
    ### end Alembic commands ###
