"""empty message

Revision ID: d094feb62433
Revises: 5206ce7720c5
Create Date: 2016-06-04 15:33:24.386871

"""

# revision identifiers, used by Alembic.
revision = 'd094feb62433'
down_revision = '5206ce7720c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12), nullable=False),
    sa.Column('timestamp', sa.DECIMAL(precision=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price'),
    sa.UniqueConstraint('timestamp')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    ### end Alembic commands ###
